name: "Build Site and Deploy"

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install Nix
      uses: cachix/install-nix-action@v12
      with:
        install_url: https://github.com/numtide/nix-flakes-installer/releases/download/nix-2.4pre20201221_9fab14a/install
        extra_nix_config: |
          experimental-features = nix-command flakes
    - name: Build
      run: nix run ./#compile
    - name: Deploy
      id: ipfs
      if: success()
      uses: aquiladev/ipfs-action@v0.1.5
      with:
        path: ./out
        service: pinata
        pinataKey: ${{ secrets.API_KEY }}
        pinataSecret: ${{ secrets.API_SECRET }}
    - name: Update dns
        if: success()
        run: curl --basic -u "${{ secrets.YDNS_USER }}:${{ secrets.YDNS_PASSWORD }}" https://ydns.io/api/v1/update/?host=pippo.dyn.ydns.io&record_id=166019&ip=${{ steps.ipfs.hash }}

