name: "Build Site and Deploy"

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    #- uses: actions/checkout@v1
    #- name: Install Nix
    #  uses: cachix/install-nix-action@v12
    #  with:
    #    install_url: https://github.com/numtide/nix-flakes-installer/releases/download/nix-2.4pre20201221_9fab14a/install
    #    extra_nix_config: |
    #      experimental-features = nix-command flakes
    #- name: Build
    #  run: nix run ./#compile
    - name: Create file
      run: echo "hello world" > file  
    - name: Deploy
      id: ipfs
    #  if: success()
      uses: aquiladev/ipfs-action@v0.1.5
      with:
        path: ./file
        service: pinata
        pinataKey: ${{ secrets.API_KEY }}
        pinataSecret: ${{ secrets.API_SECRET }}
    - name: Update IPNS
      #if: success()
      run: curl -X POST https://api.ipfs.ccr.ydns.eu/api/v0/name/publish\?arg\=${{ steps.ipfs.outputs.hash }}\&key\=blog

